# Problem 1

In [ ]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin


In [3]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 5.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

# Matris oluşturma
matris = np.random.randint(0, 10, size=(5))

# Matris boyutunu öğrenme
boyut = matris.shape
print("Matris boyutu:", boyut)

# Matris yeniden boyutlandırma
matris = matris.reshape((1, 5))

# Matris boyut sayısını öğrenme
boyut_sayisi = matris.ndim
print("Matris boyut sayısı:", boyut_sayisi)

Matris boyutu: (5,)
Matris boyut sayısı: 2


# Problem 2

In [ ]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin


In [8]:
import numpy as np

# Matris oluşturma
matris = np.arange(1, 10, 2).reshape((5, 1))
print("Oluşturulan matris:\n", matris)

# Matrisin boyutunu öğrenme
boyut = matris.shape
print("Matrisin boyutu:", boyut)

# Matrisi yeniden boyutlandırma
yeniden_boyutlandirilmis_matris = matris.reshape((1, 5))
print("Yeniden boyutlandırılmış matris:\n", yeniden_boyutlandirilmis_matris)

# Yeniden boyutlandırılmış matrisin boyutunu öğrenme
yeniden_boyutlandirilmis_boyut = yeniden_boyutlandirilmis_matris.shape
print("Yeniden boyutlandırılmış matrisin boyutu:", yeniden_boyutlandirilmis_boyut)

Oluşturulan matris:
 [[1]
 [3]
 [5]
 [7]
 [9]]
Matrisin boyutu: (5, 1)
Yeniden boyutlandırılmış matris:
 [[1 3 5 7 9]]
Yeniden boyutlandırılmış matrisin boyutu: (1, 5)


# Problem 3

In [ ]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin


In [10]:
np.ones((5,3))

# bu yazımda demet şeklinde yazmaya dikkat et yanı kaç tane kaç elemandan olacak derken burada demetler ve sayılar öbemlidir 
# ilk satır kac tane array yapısı olacak ona karar verir diğer sayı ise ondan kaç adet olacak ona karar verir

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
import numpy as np

# Matris oluşturma
matris = np.arange(5, 101, 2)[:10].reshape(2, 5)
print("Oluşturulan matris:\n", matris)

# Matrisin boyutunu öğrenme
boyut = matris.shape
print("Matrisin boyutu:", boyut)

# Matrisin veri tipini öğrenme
veri_tipi = matris.dtype
print("Matrisin veri tipi:", veri_tipi)

# Matrisin eleman sayısını öğrenme
eleman_sayisi = matris.size
print("Matrisin eleman sayısı:", eleman_sayisi)

# Matrisin boyut sayısını öğrenme
boyut_sayisi = matris.ndim
print("Matrisin boyut sayısı:", boyut_sayisi)

Oluşturulan matris:
 [[ 5  7  9 11 13]
 [15 17 19 21 23]]
Matrisin boyutu: (2, 5)
Matrisin veri tipi: int32
Matrisin eleman sayısı: 10
Matrisin boyut sayısı: 2
